export default {
  carousel1: require("../assets/images/carousel1.jpg"),
  carousel2: require("../assets/images/carousel2.jpg"),
  carousel3: require("../assets/images/carousel3.webp"),
  banner1: require("../assets/images/banner-02.jpg"),
  banner2: require("../assets/images/banner-07.jpg"),
  banner3: require("../assets/images/shop-item-09.jpg"),
  banner4: require("../assets/images/banner-08.jpg"),
  item1: require("../assets/images/item-cart-01.jpg"),
  item2: require("../assets/images/item-cart-02.jpg"),
  item3: require("../assets/images/item-cart-03.jpg"),
  item4: require("../assets/images/item-05.jpg"),
  item5: require("../assets/images/item-02.jpg"),
  item6: require("../assets/images/item-03.jpg"),
  item7: require("../assets/images/item-07.jpg"),
  pngItem1: require("../assets/images/item-05.png"),
  pngItem2: require("../assets/images/item-cart-03.png"),
  carouselImg1: require("../assets/images/2ndCarouselImg.webp"),
  carouselImg2: require("../assets/images/2ndCarouselImg2.webp"),
  carouselImg3: require("../assets/images/2ndCarouselImg3.webp"),
  carouselImg4: require("../assets/images/2ndCarouselImg4.webp"),
  carouselImg5: require("../assets/images/2ndCarouselImg5.webp"),
  carouselImg6: require("../assets/images/2ndCarouselImg6.webp"),
  carouselImg7: require("../assets/images/2ndCarouselImg7.webp"),
  blog1: require("../assets/images/blog-01.jpg"),
  blog2: require("../assets/images/blog-02.jpg"),
  blog3: require("../assets/images/blog-03.jpg"),
};
